---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Descarga y descomprime focalboard
  ansible.builtin.unarchive:
    src: "{{ focal_url }}"
    dest: /opt
    owner: "root"
    group: "root"
    mode: 0755
    remote_src: true

- name: copiando configuracion 
  ansible.builtin.template:
    src: "files/{{ focal_conf }}.j2"
    dest: "/opt/focalboard/{{ focal_conf }}"

- name: copiando servicio
  ansible.builtin.template:
    src: "files/{{ focal_service }}"
    dest: "/lib/systemd/system/{{ focal_service }}"
  notify: servicios_focalboard